//
// Created by kkeiper1103 on 5/13/2023.
//

#ifndef PREDATION_PREDATION_H
#define PREDATION_PREDATION_H

#define BUTTON_HEIGHT 42
#define MENU_WIDTH 300
#define MENU_HEIGHT 340

#endif //PREDATION_PREDATION_H
